# Generated by Django 6.0.4 on 2026-06-04 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='task',
            name='supervisors',
            field=models.ManyToManyField(related_name='supervised_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'account created'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('MEMBER_REMOVED', 'User Removed from Workspace'), ('MEMBER_LEFT', 'User left from Workspace'), ('ACCOUNT_PURGED', 'Account Deleted'), ('GENERAL_UPDATE', 'General update'), ('REPORT_REVIEWED', 'rerport reviewde'), ('INVITATION_SENT', 'Invitation Sent'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('INVITATION_REJECTED', 'Invitation Rejected')], default='GENERAL_UPDATE', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'TASK_UNASSIGNED'), ('SYSTEM_ALERT', 'System Alert'), ('COMMENT_ADDED', 'New Comment'), ('REPORT_REJECTED', 'Report Rejected'), ('REPORT_SUBMITTED', 'Report Submitted'), ('INVITATION_RECEIVED', 'Invitation Received'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('INVITATION_REJECTED', 'Invitation Rejected')], default='SYSTEM_ALERT', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin '), ('EMPLOYEE', 'employee'), ('MANAGER', 'Manager')], default='EMPLOYEE', max_length=10),
        ),
    ]
