# Generated by Django 5.1 on 2026-07-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='users_task_workspa_c56243_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workspace',
        ),
    ]
