# Generated by Django 6.0.4 on 2026-06-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_task_supervisor_task_supervisors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'account created'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('MEMBER_REMOVED', 'User Removed from Workspace'), ('MEMBER_LEFT', 'User left from Workspace'), ('ACCOUNT_PURGED', 'Account Deleted'), ('GENERAL_UPDATE', 'General update'), ('REPORT_REVIEWED', 'Report Reviewed'), ('INVITATION_SENT', 'Invitation Sent'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('INVITATION_REJECTED', 'Invitation Rejected'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_UPDATED', 'Request Updated'), ('REQUEST_DELETED', 'Request Deleted'), ('REQUEST_REVIEWED', 'Request Reviewed'), ('REPORT_DRAFT_CREATED', 'Report Draft Created'), ('REPORT_DRAFT_UPDATED', 'Report Draft Updated'), ('REPORT_DELETED', 'Report Deleted'), ('REPORT_SUBMITTED', 'Report Submitted'), ('ROLE_UPDATED', 'ROLE_UPDATED')], default='GENERAL_UPDATE', max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DEV', 'Developer'), ('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager')], default='EMPLOYEE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=20),
        ),
    ]
