# Generated by Django 5.1 on 2026-07-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_archive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'account created'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('MEMBER_REMOVED', 'User Removed from Workspace'), ('MEMBER_LEFT', 'User left from Workspace'), ('ACCOUNT_PURGED', 'Account Deleted'), ('GENERAL_UPDATE', 'General update'), ('REPORT_REVIEWED', 'Report Reviewed'), ('INVITATION_SENT', 'Invitation Sent'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('INVITATION_REJECTED', 'Invitation Rejected'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_UPDATED', 'Request Updated'), ('REQUEST_DELETED', 'Request Deleted'), ('REQUEST_REVIEWED', 'Request Reviewed'), ('REPORT_DRAFT_CREATED', 'Report Draft Created'), ('REPORT_DRAFT_UPDATED', 'Report Draft Updated'), ('REPORT_DELETED', 'Report Deleted'), ('REPORT_SUBMITTED', 'Report Submitted'), ('ROLE_UPDATED', 'ROLE_UPDATED'), ('BULK_TASK_UPDATED', 'Bulk Task Updated'), ('WORKSPACE_ARCHIVED', 'Workspace Archived'), ('WORKSPACE_RESTORED', 'Workspace Restored'), ('PROJECT_ARCHIVED', 'Project Archived'), ('PROJECT_RESTORED', 'Project Restored'), ('TASK_ARCHIVED', 'Task Archived'), ('TASK_RESTORED', 'Task Restored')], default='GENERAL_UPDATE', max_length=100),
        ),
    ]
