
# Generated by Django 5.1 on 2026-07-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_align_activity_notification_choices'),
        ('users', '0007_alter_activitylog_action'),
    ]

    operations = [
    ]
