# Generated by Django 5.1 on 2026-07-28 23:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20260729_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestform',
            name='leave_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='leave_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestform',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available_for_tasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'account created'), ('WORKSPACE_CREATED', 'Workspace Created'), ('WORKSPACE_UPDATED', 'Workspace Updated'), ('WORKSPACE_DELETED', 'Workspace Deleted'), ('WORKSPACE_LEFT', 'Workspace Left'), ('WORKSPACE_OWNERSHIP_TRANSFERRED', 'Workspace Ownership Transferred'), ('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_LEFT', 'Project Left'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'Task Unassigned'), ('TASK_DELETED', 'Task Deleted'), ('MEMBER_ADDED', 'User Added'), ('MEMBER_REMOVED', 'User Removed from Workspace'), ('MEMBER_LEFT', 'User left from Workspace'), ('ACCOUNT_PURGED', 'Account Deleted'), ('GENERAL_UPDATE', 'General update'), ('REPORT_REVIEWED', 'Report Reviewed'), ('INVITATION_SENT', 'Invitation Sent'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('INVITATION_REJECTED', 'Invitation Rejected'), ('REQUEST_CREATED', 'Request Created'), ('REQUEST_UPDATED', 'Request Updated'), ('REQUEST_DELETED', 'Request Deleted'), ('REQUEST_REVIEWED', 'Request Reviewed'), ('REPORT_DRAFT_CREATED', 'Report Draft Created'), ('REPORT_DRAFT_UPDATED', 'Report Draft Updated'), ('REPORT_DELETED', 'Report Deleted'), ('REPORT_SUBMITTED', 'Report Submitted'), ('BUG_REPORTED', 'Bug Reported'), ('BUG_UPDATED', 'Bug Updated'), ('BUG_DELETED', 'Bug Deleted'), ('BUG_CONVERTED_TO_TASK', 'Bug Converted To Task'), ('ROLE_UPDATED', 'Role Updated'), ('BULK_TASK_UPDATED', 'Bulk Task Updated'), ('WORKSPACE_ARCHIVED', 'Workspace Archived'), ('WORKSPACE_RESTORED', 'Workspace Restored'), ('PROJECT_ARCHIVED', 'Project Archived'), ('PROJECT_RESTORED', 'Project Restored'), ('TASK_ARCHIVED', 'Task Archived'), ('TASK_RESTORED', 'Task Restored')], default='GENERAL_UPDATE', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UNASSIGNED', 'TASK_UNASSIGNED'), ('SYSTEM_ALERT', 'System Alert'), ('COMMENT_ADDED', 'New Comment'), ('REPORT_REJECTED', 'Report Rejected'), ('REPORT_SUBMITTED', 'Report Submitted'), ('INVITATION_RECEIVED', 'Invitation Received'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('INVITATION_REJECTED', 'Invitation Rejected'), ('BUG_REPORTED', 'Bug Reported'), ('BUG_CLOSED', 'Bug Closed'), ('BUG_CONVERTED_TO_TASK', 'Bug Converted To Task')], default='SYSTEM_ALERT', max_length=30),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTION_REQUIRED', 'Action Required'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True, verbose_name='Actual Worked Duration'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_duration',
            field=models.DurationField(verbose_name='Expected Duration'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('REVIEW', 'Review'), ('DONE', 'Done'), ('PAUSED', 'Paused'), ('PAUSED', 'Paused')], default='TODO', max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveTaskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(blank=True, choices=[('NO_ACTION', 'No Action'), ('TRANSFER_TASK', 'Transfer Task'), ('EXTEND_DUE_DATE', 'Extend Due Date'), ('PAUSE_TASK', 'Pause Task')], max_length=30, null=True)),
                ('new_due_date', models.DateTimeField(blank=True, null=True)),
                ('previous_task_status', models.CharField(blank=True, max_length=30, null=True)),
                ('impact', models.CharField(choices=[('COMPLETED', 'Completed'), ('NO_DUE_DATE', 'No Due Date'), ('CAN_FINISH_BEFORE_LEAVE', 'Can Finish Before Leave'), ('NOT_ENOUGH_TIME_BEFORE_LEAVE', 'Not Enough Time Before Leave'), ('DUE_DURING_LEAVE', 'Due During Leave'), ('CAN_FINISH_AFTER_RETURN', 'Can Finish After Return'), ('NOT_ENOUGH_TIME_AFTER_RETURN', 'Not Enough Time After Return')], max_length=40)),
                ('requires_action', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('new_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_transferred_tasks', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_task_actions', to='users.requestform')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_leave_task_actions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_actions', to='users.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('request', 'task'), name='unique_task_per_leave_request')],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_type', models.CharField(choices=[('BLOCKS', 'Blocks'), ('RELATED', 'Related')], default='BLOCKS', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_dependencies', to=settings.AUTH_USER_MODEL)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks', to='users.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dependencies', to='users.task')),
            ],
            options={
                'indexes': [models.Index(fields=['predecessor'], name='users_taskd_predece_5c8953_idx'), models.Index(fields=['successor'], name='users_taskd_success_a72436_idx'), models.Index(fields=['dependency_type'], name='users_taskd_depende_44bd6b_idx')],
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor', 'dependency_type'), name='unique_task_dependency'), models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='prevent_task_self_dependency')],
            },
        ),
    ]
