# Generated by Django 5.1 on 2026-07-29 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_requestform_leave_end_requestform_leave_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetaskaction',
            name='previous_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_leave_task_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetaskaction',
            name='previous_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTION_REQUIRED', 'Action Required'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('REVIEW', 'Review'), ('DONE', 'Done'), ('PAUSED', 'Paused')], default='TODO', max_length=20),
        ),
    ]
