# Generated by Django 5.1 on 2026-08-06 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_leavetaskaction_previous_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetaskaction',
            name='action',
            field=models.CharField(blank=True, choices=[('NO_ACTION', 'No Action'), ('TRANSFER_TASK', 'Transfer Task'), ('EXTEND_DUE_DATE', 'Extend Due Date'), ('PAUSE_TASK', 'Pause Task'), ('REVIEW_REPORT', 'Review Report')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='BugTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='users.bugreportform')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bug_task_links', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bug_link', to='users.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bug', 'task'), name='unique_bug_task_link')],
            },
        ),
    ]
