# Generated by Django 5.1 on 2026-08-18 12:53

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_leavetaskaction_action_bugtasklink'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceWorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.JSONField(default=users.models.default_working_days, help_text='Working days: MON,TUE,WED,THU,FRI,SAT,SUN')),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_schedule', to='users.workspace')),
            ],
        ),
    ]
