# Generated by Django 5.1 on 2026-08-18 13:14

from django.db import migrations


def create_default_schedules(apps, schema_editor):

    WorkSpace = apps.get_model(
        "users",
        "WorkSpace"
    )

    WorkspaceWorkingSchedule = apps.get_model(
        "users",
        "WorkspaceWorkingSchedule"
    )

    schedules = []

    for workspace in WorkSpace.objects.all():

        schedules.append(
            WorkspaceWorkingSchedule(
                workspace=workspace,
                working_days=[
                    "MON",
                    "TUE",
                    "WED",
                    "THU",
                    "FRI",
                ],
                start_time="09:00",
                end_time="17:00",
                timezone="UTC",
                is_24_hours=False,
            )
        )

    WorkspaceWorkingSchedule.objects.bulk_create(
        schedules
    )




class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_workspaceworkingschedule'),
    ]


    operations = [
        migrations.RunPython(
            create_default_schedules
        ),
    ]