# Generated by Django 5.1 on 2026-08-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20260818_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceworkingschedule',
            name='weekly_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
