# Generated by Django 5.1 on 2026-08-19 00:31

from django.db import migrations
from django.db import migrations


def populate_weekly_schedule(apps, schema_editor):

    WorkspaceWorkingSchedule = apps.get_model(
        "users",
        "WorkspaceWorkingSchedule"
    )

    default_weekly_schedule = {
        "MON": {
            "enabled": True,
            "start": "09:00",
            "end": "17:00",
        },
        "TUE": {
            "enabled": True,
            "start": "09:00",
            "end": "17:00",
        },
        "WED": {
            "enabled": True,
            "start": "09:00",
            "end": "17:00",
        },
        "THU": {
            "enabled": True,
            "start": "09:00",
            "end": "17:00",
        },
        "FRI": {
             "enabled": True,
                       "start": "09:00",
                       "end": "17:00",
        },
        "SAT": {
            "enabled": True,
                      "start": "09:00",
                      "end": "17:00",
        },
        "SUN": {
             "enabled": True,
                       "start": "09:00",
                       "end": "17:00",
        },
    }

    schedules = WorkspaceWorkingSchedule.objects.all()

    for schedule in schedules:
        schedule.weekly_schedule = default_weekly_schedule
        schedule.save(
            update_fields=["weekly_schedule"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_workspaceworkingschedule_weekly_schedule"),
    ]

    operations = [
        migrations.RunPython(
            populate_weekly_schedule
        ),
    ]