# Generated by Django 5.1 on 2026-08-19 12:54

from django.db import migrations

from django.db import migrations


DEFAULT_WEEKLY_SCHEDULE = {
    "MON": {
        "enabled": True,
        "start": "09:00",
        "end": "17:00",
    },
    "TUE": {
        "enabled": True,
        "start": "09:00",
        "end": "17:00",
    },
    "WED": {
        "enabled": True,
        "start": "09:00",
        "end": "17:00",
    },
    "THU": {
        "enabled": True,
        "start": "09:00",
        "end": "17:00",
    },
    "FRI": {
        "enabled": True,
        "start": "09:00",
        "end": "17:00",
    },
    "SAT": {
        "enabled": True,
        "start": "09:00",
        "end": "17:00",
    },
    "SUN": {
        "enabled": True,
        "start": "09:00",
        "end": "17:00",
    },
}


def update_weekly_schedule(apps, schema_editor):
    WorkspaceWorkingSchedule = apps.get_model(
        "users",
        "WorkspaceWorkingSchedule"
    )

    for schedule in WorkspaceWorkingSchedule.objects.all():
        schedule.weekly_schedule = DEFAULT_WEEKLY_SCHEDULE
        schedule.save(update_fields=["weekly_schedule"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_populate_weekly_schedule"),
    ]

    operations = [
        migrations.RunPython(
            update_weekly_schedule,
            migrations.RunPython.noop,
        ),
    ]
