# Generated by Django 5.1 on 2026-08-19 13:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20260819_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceworkingschedule',
            name='weekly_schedule',
            field=models.JSONField(blank=True, default=users.models.default_weekly_schedule),
        ),
    ]
