# Generated by Django 5.1 on 2026-08-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_workspaceworkingschedule_weekly_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
